services:
  # --- tailscale (exit-node) ---
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - tailscale-var-lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --hostname=${TS_HOSTNAME:-kr-exit-node}

  # --- PostgreSQL ---
  postgres_db:
    container_name: postgres_db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-autotrade}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autotrade_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-autotrade}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Qdrant (커스텀 이미지) ---
  qdrant_db:
    container_name: qdrant_db
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    restart: unless-stopped
    environment:
      QDRANT_API_KEY: ${QDRANT_API_KEY:-}
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - autotrade_net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6333/collections"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # --- Grafana ---
  grafana_dashboard:
    container_name: grafana_dashboard
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      postgres_db:
        condition: service_healthy
      qdrant_db:
        condition: service_healthy
    networks:
      - autotrade_net

  # --- Autotrade API ---
  autotrade_app:
    container_name: autotrade_app
    build:
      context: ./KIS_ETF_Autotrade
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./KIS_ETF_Autotrade/.env
    # PATH 에 uvicorn 스크립트가 없으므로 python -m 으로 실행
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - app_logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant_db
      - QDRANT_PORT=6333
      - QDRANT_URL=http://qdrant_db:6333
    depends_on:
      postgres_db:
        condition: service_healthy
      qdrant_db:
        condition: service_healthy
    networks:
      - autotrade_net

  # --- Discord Bot ---
  discord_bot:
    container_name: discord_bot
    build:
      context: ./KIS_ETF_Autotrade
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./KIS_ETF_Autotrade/.env
    working_dir: /app
    command: ["python", "-m", "src.discord.bot"]
    volumes:
      - app_logs:/app/logs
    depends_on:
      autotrade_app:
        condition: service_started
    networks:
      - autotrade_net

volumes:
  tailscale-var-lib:
  postgres_data:
  qdrant_storage:
  grafana_data:
  app_logs:

networks:
  autotrade_net:
    external:
      name: ubuntu_autotrade_net